version: '3.8'

services:
  # PostgreSQL database service
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Resheh-2019
      POSTGRES_DB: powerplantapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Node.js application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://root:Resheh-2019@postgres:5432/powerplantapp
      - SESSION_SECRET=local_development_secret_change_this_in_production
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data: